        !COMPILER-GENERATED INTERFACE MODULE: Sat Jan 01 18:24:03 2022
        MODULE CLOSE_POT__genmod
          INTERFACE 
            SUBROUTINE CLOSE_POT
            END SUBROUTINE CLOSE_POT
          END INTERFACE 
        END MODULE CLOSE_POT__genmod
