        !COMPILER-GENERATED INTERFACE MODULE: Sat Jan 01 18:24:03 2022
        MODULE INIT_POT__genmod
          INTERFACE 
            SUBROUTINE INIT_POT(NAME,INITOK,ICM)
              CHARACTER(*) :: NAME
              INTEGER(KIND=4) :: INITOK
              INTEGER(KIND=4) :: ICM
            END SUBROUTINE INIT_POT
          END INTERFACE 
        END MODULE INIT_POT__genmod
